apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:q5Pj5XdsCpBZIEimoPxj4XSnp2D4qa5UtleD8qxw3TDWjSH/CorPHEZANG7K8IU7kQMP4OcKwBNeXje3DILoLP5WA/xVePG7HIzhmfgXAp8gVn5L6OnMblENqZTIupNTF1bHPLguAFMOyH4nfKbLUJCIti4NNF/6z+QY3PAx5ZFqAh5cbp6gup+LcBq/hXLZD+Gp66IXsbaSYBp/ZoOxKlkDQXMAXMcZ7iaYmosI3B/GGcMb0OPt0HoG2Ba+0/FadmF0qcm898NZhANmrtDWc7bU4lJBaf+f+KFPGh5KwZEXrPEy+5fwDVGo0CY=,iv:B0IP2ql7IUC2lMUwguFg83XvWW6sJt9dyGH2IbsSCE8=,tag:EuZGoE1jijBO74jHxLdB3A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZjdQeERQV0lCRUczVkpa
            cWREWjlZK0lkQ08xa2ZwSXdjOUZaNERuVm5NCmhIckN4azc1Q0dDQW9oVzQ5b05Z
            R0JXbU96MGpkc21XSHdFcW9qTDI2aEUKLS0tIEY4aVpRY3lLd3E0MmZVUVlaMlUy
            dWFNYjJtUG1iOFZNOTUwRU9nRkVYbTAKK+QS2DJ+l2496a1PXQaXMZLOBDGcCjmM
            d2z8Sh3SFWZ8uvAFPsA+da6jeEROcN6MHRMVlq4Mvcb4igaopN4p6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19c7qmsz2zke24lge0spsxw060wuv7dt279smdjzt5l9ly9wa9qtshd9chn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T21:10:56Z"
    mac: ENC[AES256_GCM,data:iWLYmMG3Hp5Iu5KLC4/yWggkRaVfpn7vMwM034X66+cmP6mc7Tp3v2axBqUHkXQ/4/8PZ9DWO6jWc7kMpC+l2v1pzs633UD1JuEwhO0QRThtUNqpKxRVWGxZnpgCo1OhznaJTGiUaNNvsJjjkCG3Rkr+PTyXLZhPKC9PH77Q6Gw=,iv:BU+xvMUEP9NHgkD4yDHLJJxr8Etv2+SLFXUdqZ8Ixjg=,tag:SYLyBslviSpsID+LhDVC6g==,type:str]
    version: 3.13.1
