apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy: {}
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.35.1
        name: audiobookshelf

        envFrom:
          - configMapRef:
              name: audiobookshelf-configmap
        resources: {}

        volumeMounts:
          - name: audiobookshelf-config
            mountPath: /config
          - name: audiobookshelf-metadata
            mountPath: /metadata
          - name: audiobookshelf-audiobooks
            mountPath: /audiobooks

      volumes:
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks
    securityContext:
      allowPrivilegeEscalation: false
status: {}
