apiVersion: v1
kind: Service
metadata:
  labels:
    app: audiobookshlef
  name: audiobookshlef
spec:
  ports:
  - name: "3005"
    port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: audiobookshlef
  type: ClusterIP
status:
  loadBalancer: {}
