apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ia6MznHWF3Tm2wgUf/EN/tJMkuCNegiDEX4UZqB/BhRjcgYyJPOeSKXYGGuTRAgqG/ghOycKD7knl76ue0+OAIrMDYzYJcbT0Mgzv7xGGTiDhBnJdcqB4V7NvYjOOvz+cBUuWCXzLjHdiYdWgBdZLBY/OUuDMVmMN37YgBVhlZE/V7PuEZA3H7VOcD49Xr+icaKlHpmg21i2peoB6GJ4PziAlXIOl1pBZLj6R11rCZnQUzvoaQ5yRNIyzoA0IJhDGRAATUcVmjnwnD5GGetK2rCHyPvfEZGfb1XZsSvu6GPS8qg/mbLi8HfDg+M=,iv:OXxzZWMmFk79OEXAW02vcyuK8lqB+ycX635A1tA3MeU=,tag:zj13Yc+VbmAQkTFkgBxxhA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc1hzbEZwOUpTRGNUOXdC
            eEF3aW1FdE91KzVFYzRoYXA5Q2tFZ0p1ZmpNCjNJbHVYUkpyUTRUWHVUZXVtMHl2
            dFBkUVQ1eE1UeWFuWHVIbURHWDNtUEkKLS0tIG9rMVNBZC91T015L1d3dlliRS83
            ajBxUUw3cTFkZ0hQMDFGRWozSjFxK2sK+u0a910G20r19c9zy3QxEMP8tGCE3Jyt
            B8PHV1sWhyM8mVwtgtfqXBinvYCGQO2JaG+ffHMIP0DMoJiGKt/vvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19c7qmsz2zke24lge0spsxw060wuv7dt279smdjzt5l9ly9wa9qtshd9chn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T12:27:51Z"
    mac: ENC[AES256_GCM,data:IvSVmNjHWJxq55vRRv3T0EKLbNxXXH1xskOVUxxXPKzYicscAqBc6KodThf6WtmR3pizFZJGMm19jMTVjoMIXmnRyM42GaEZGevjEFa8OWG7Rt3cowxUO+2Vgt6Dw98ExV4Sbip69j33222SW8bAKSlDUNhDZzcMxl+cY6zJimo=,iv:ePdf5yMQIKROspM8SNiac5rKlTtCXQefnNhxKHmTtx0=,tag:vPx3NOSqM4r43ooFU0MU0g==,type:str]
    version: 3.13.1
