apiVersion: v1
data:
    password: ENC[AES256_GCM,data:QkCgJf761HA=,iv:5+JA6jKadRURa8OcA5UIDpM0lokugVSzmRZWpF162TE=,tag:aJGPTxj+03Ff8RplIk3Kkw==,type:str]
    user: ENC[AES256_GCM,data:fdm5jFjjGYM=,iv:vCWUghQrpCb6v0vc1kcEb7Ho5SH+9ewPr5Zh/pjaHOE=,tag:xBGNJOn9DL74HnaVMt70OQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc1dkcmk1UVkvMDJiTlVB
            cndnL2txcTd2OVJlNFZrZnpickgveHNqNkNNCjFCUXN4clgzaEJWQXZ4ZjFxME5K
            RTY1NFR5eWJ3UVIwNTk5bUtpb1N6QkUKLS0tIGRUejh4UFJEOW1ZUEM0K0gydG5J
            Qys3a21iZHNMcGVhTkhMRXJIcENzN0EKgly6mbHbR7yAysxa3wi8OOs8xcEQzWC0
            Kk8DjV7ml3+R9ycZ+gqf/rMVNw2CI6BaVoUUprWqqykuEl527VbMzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19c7qmsz2zke24lge0spsxw060wuv7dt279smdjzt5l9ly9wa9qtshd9chn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T11:01:54Z"
    mac: ENC[AES256_GCM,data:jMZzQoHpoi00KBTBzGUpI6dwP/rd9sI2mcXQu0skDNf3X+VzP3ADmcs7+aNf4h1rSSw4AsbC194VH38GuJzvyf/WctJ0yPmLbCeYWI9fig+ngh67TJGY2kYJd/W7MeNHyIAe3HBh5F/belLpgp+si4ibwHUt/TJNJU6y9HK7Wp0=,iv:pCcv9/q0EPxNYjSHpeNabWsuXRhzG3BCT8bQrdINmiA=,tag:j8eLces/GH26vouJ2+S6OA==,type:str]
    version: 3.13.1
